### PR TITLE
Add doc for DSP

### PR DESCRIPTION
**Pull request by yufeiyu**
#### What type of PR is this?
doc

#### What this PR does / why we need it:
tutorial doc for DSP algorithm

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Review by qmhu — COMMENTED** [review]
Better to put related images into a sub folder ,  e.g. docs/images/algorithm/

**Comment by yufeiyu** [comment]
> Better to put related images into a sub folder , e.g. docs/images/algorithm/

done

**Review by xieydd — APPROVED** [review]
LGTM

**Comment by yufeiyu** [comment]
> LGTM, but we need fix ci error in https://github.com/gocrane/crane/runs/7353097449?check_suite_focus=true
> 
> ```
> golangci-lint ...
> ```

fixed

**Review by qmhu — APPROVED** [review]
/LGTM

**Pull request merged**
