### PR TITLE
add local env setup from mirror helm repo

### PR DESCRIPTION
**Pull request by 2456868764**
#### What type of PR is this?
add  local-env-setup from mirror helm repo 

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by qmhu** [comment]
Welcome to contribute @2456868764 .
We have a local-env-setup script now ,so it can be a args in it, the default address is official address, and user can set to mirror by args.

**Comment by 2456868764** [comment]
> Welcome to contribute @2456868764 . We have a local-env-setup script now ,so it can be a args in it, the default address is official address, and user can set to mirror by args.
i feel like to be one it , do u mind assigning impovement to me?

**Comment by 2456868764** [comment]
got it

**Comment by 2456868764** [comment]
i have added args local-en-setup.sh,  please review.

**Review by qmhu — APPROVED** [review]

**Pull request merged**
