### PR TITLE
[WIP][Help] Support web docs by mkdocs

### PR DESCRIPTION
**Pull request by zsnmwy**
#### What type of PR is this?

Support web docs by mkdocs.

Demo: https://zsnmwy.github.io/crane/

#### Help

Because of the markdown parser, I need to change a lot of docs formats.
Please check all docs.

### CODE REVIEW

**Comment by qmhu** [comment]
Please squash your commits into one.

**Comment by zsnmwy** [comment]
You must exec the below commands to make sure the web access is normal after merged. 

But if you **_create a new release branch immediately_**, you can ignore the actions that follow.

```shell
mike set-default --push --force dev # Will be gen an index.html. That used to redirect uri.
```

```HTML
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Redirecting</title>
  <noscript>
    <meta http-equiv="refresh" content="1; url=latest/" />
  </noscript>
  <script>
    window.location.replace("dev/" + window.location.hash); <!-- Like 301 or 302 -->
  </script>
</head>
<body>
  Redirecting to <a href="dev/">latest/</a>...
</body>
</html>
```
---

### Why

https://github.com/gocrane/crane/blob/24cd5d611c53f3f74787a835020fdd87cca94472/.github/workflows/mkdocs.yml#L21

When pr is merged, the GitHub actions - `mkdocs.yml` will be triggered.

`mike` will gen a static document site base on the main branch and force push to `gh-pages`.

The bad thing is that mike won't create `index.html` for you when this command is used.

**But don't worry, everything will be normal next.**

https://github.com/gocrane/crane/blob/24cd5d611c53f3f74787a835020fdd87cca94472/.github/workflows/mkdocs-publish.yml#L31-L36

When you create a new release branch, `mike` will automatically set up the latest branch for you.

**Comment by zsnmwy** [comment]
# Crane PR Docs Preview

https://github.com/zsnmwy/crane/pull/1
https://github.com/zsnmwy/crane/pull/2

https://zsnmwy-crane-preview-pr-2.surge.sh/

**Comment by qmhu** [comment]
@zsnmwy  CI progress failed...

**Comment by zsnmwy** [comment]
> @zsnmwy CI progress failed...

`afc163/surge-preview@v1` try to comment on this pr but failed.

It seems to have some permission issues for the `GITHUB_TOKEN`.

image

[permissions-for-the-github_token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)


I try to fix it.

**Pull request merged**
