### PR TITLE
Use caddy to replace nginx

### LINKED ISSUE #235: Start dashboard failed when grafana not exist
**Describe the bug**

Start dashboard failed when grafana not exist

**Reproduce steps**

skip grafana deployment, when we install craned, it will failed.

**Expected behavior**

craned should running.

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: [e.g. 1.19]
 - Crane Version: [e.g. 0.1.0] v0.3.0

### PR DESCRIPTION
**Pull request by lbbniu**
#### What type of PR is this?

Fix bug

#### What this PR does / why we need it:

Solve that the grafana service is not created, and the dashboard cannot be started.

#### Which issue(s) this PR fixes:

Fixes #235

### CODE REVIEW

**Comment by zsnmwy** [comment]
I think Nginx is more common than Caddy. 
Better for people to reference.

**Comment by lbbniu** [comment]
The service used by upstream in nginx is not created, nginx cannot be started, is there a better way to start nginx?

**Comment by zsnmwy** [comment]
> The service used by upstream in nginx is not created, nginx cannot be started, is there a better way to start nginx?

Is it possible to provide a sample for this case?

**Comment by lbbniu** [comment]
> > The service used by upstream in nginx is not created, nginx cannot be started, is there a better way to start nginx?
> 
> Is it possible to provide a sample for this case?
https://github.com/gocrane/crane/issues/235
Do not deploy grafana, directly deploy crane

**Comment by zsnmwy** [comment]
We can use var to avoid Nginx starting to fail when upstream fails.
But it needs to point DNS to the K8S cluster.

```nginx
server {
    # this is the internal DNS, the cache only for the 30s
    resolver 127.0.0.11 valid=30s;
    
    location ^~ /api/ {
        # other config entries omitted for breavity
    
        set $upstream api.awesome.com:9000;
 
        # nginx will now start if host is not reachable
        fastcgi_pass    $upstream; 
        fastcgi_index   index.php;
    }
}
```
Ref: https://sandro-keil.de/blog/let-nginx-start-if-upstream-host-is-unavailable-or-down/

**Comment by lbbniu** [comment]
This method is not reliable, how to dynamically obtain the dns address?

**Comment by lbbniu** [comment]
> We can use var to avoid Nginx starting to fail when upstream fails. But it needs to point DNS to the K8S cluster.
> 
> ```nginx
> server {
>     # this is the internal DNS, the cache only for the 30s
>     resolver 127.0.0.11 valid=30s;
>     
>     location ^~ /api/ {
>         # other config entries omitted for breavity
>     
>         set $upstream api.awesome.com:9000;
>  
>         # nginx will now start if host is not reachable
>         fastcgi_pass    $upstream; 
>         fastcgi_index   index.php;
>     }
> }
> ```
> 
> Ref: https://sandro-keil.de/blog/let-nginx-start-if-upstream-host-is-unavailable-or-down/

This method is not reliable, how to dynamically obtain the dns address?

**Comment by lbbniu** [comment]
And svc should be written as a complete address. If the default domain name of the deployed machine is not cluster.local, how can it be changed to obtain the cluster domain name? , and the configuration is mounted through cm? How to dynamically generate cm content? @zsnmwy

**Comment by zsnmwy** [comment]
> And svc should be written as a complete address. If the default domain name of the deployed machine is not cluster.local, how can it be changed to obtain the cluster domain name? , and the configuration is mounted through cm? How to dynamically generate cm content? @zsnmwy

I agree with you.
It's hard to make DNS correct in different clusters.
Nginx seems hard to deal with that when upstream fail.

**Pull request closed without merging**
