### PR TITLE
chore: Hide managedFields by default when display YAML

### LINKED ISSUE #504: Hide `managedFields` by default when display YAML

### PR DESCRIPTION
**Pull request by mangoGoForward**
Signed-off-by: mango <xu.weiKyrie@foxmail.com>

#### What type of PR is this?
/chore

#### What this PR does / why we need it:
Hide managedFields by default when display YAML

#### Which issue(s) this PR fixes:

Fixes #504

#### Special notes for your reviewer:
None

### CODE REVIEW

**Comment by mfanjie** [comment]
+1, I hate managedFields

**Comment by PatrickLai7528** [comment]
Removing manageField from ts declaration is not going to achieve you purpose.

Maybe you should transform yaml to js object after fetching yaml api, delete managefield property from it, then transform back to yaml and show it

**Comment by mangoGoForward** [comment]
> Removing manageField from ts declaration is not going to achieve you purpose.
> 
> Maybe you should transform yaml to js object after fetching yaml api, delete managefield property from it, then transform back to yaml and show it

Thanks, I will try

**Comment by mangoGoForward** [comment]
Hi @mfanjie @PatrickLai7528 I have tested and this screenshot like below:

image

**Review by PatrickLai7528 — APPROVED** [review]
ok

**Pull request merged**
